import Head from "next/head";
import { Layout } from "../../ui/layout/index";
import { ReportForm } from "../../components/ReportForm";
import { PostForm } from "../../components/PostForm";
import { Title, Subtitle } from "../../ui/typography/index";

const post = () => {
  return (
    <>
      <Head>
        <title>Prodigar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="w-full flex flex-col items-center justify-center gap-12 px-4">
          <Subtitle>Publica lo que quieras donar</Subtitle>
          <PostForm />
        </div>
      </Layout>
    </>
  );
};

export default post;
