import Head from "next/head";
import { Title, Subtitle, Large, Body, BodyBold, Small } from "@/ui/typography";
import { PostPreview } from "@/components/PostPreview";
import { AdminPreview } from "../components/AdminPreview";
import { MapPreview } from "components/MapPreview";
import { Contact } from "../components/Contact";
import { Layout } from "@/ui/layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Prodigar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PostPreview />
        <AdminPreview />
        <MapPreview />
        <Contact />
      </Layout>
    </>
  );
}
