import Head from 'next/head';
import Image from 'next/image';
import { Layout } from '../ui/layout/index';
import { Subtitle, Small } from '../ui/typography/index';

import avatar from '@/public/avatar.svg';

const post = () => {
  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="lg:w-2/3  flex flex-col md:flex-row items-center justify-center justify-self-center lg:px-20">
          <div className="lg:w-1/2 h-full flex flex-col justify-start items-center gap-10">
            <Image
              src={avatar}
              alt="profile"
              className="w-44 rounded-full border-4 border-custom-blue "
              width={300}
              height={300}
            />
            <Subtitle>Ayrton Juarez</Subtitle>
          </div>
          <div className="lg:w-1/2 w-full mx-auto flex items-center justify-center">
            <div className=" w-full  rounded-md bg-gradient-to-r from-pink-500 via-red-500 to-yellow-500 p-1">
              <div className="h-full w-full bg-custom-blue text-white p-4 flex flex-col gap-4">
                <Small>Ciudad:</Small>
                <Small>Direccion:</Small>
                <Small>Email:</Small>
              </div>
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
};

export default post;
